import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
<<<<<<< HEAD
  title: "Create Next App",
  description: "Generated by create next app",
=======
  title: "QuickBite - Food Delivery",
  description: "Your favorite food delivered fast",
>>>>>>> e446a20323dd918b00b8cf85b153b8a5a1890628
};

export default function RootLayout({ children }) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header></Header>

        <main className=" ">{children}</main>
      </body>
    </html>
  );
}
=======
    <html lang="en" data-theme="quickbite"> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-base-bg text-secondary`}
      >
        <Header />
        <main className="w-full min-h-screen bg-base-bg">
          {children}
        </main>
      </body>
    </html>
  );
}
>>>>>>> e446a20323dd918b00b8cf85b153b8a5a1890628
